/********************************************************************************
** Form generated from reading UI file 'mainwindow.ui'
**
** Created by: Qt User Interface Compiler version 5.5.0
**
** WARNING! All changes made in this file will be lost when recompiling UI file!
********************************************************************************/

#ifndef UI_MAINWINDOW_H
#define UI_MAINWINDOW_H

#include <QtCore/QVariant>
#include <QtWidgets/QAction>
#include <QtWidgets/QApplication>
#include <QtWidgets/QButtonGroup>
#include <QtWidgets/QFrame>
#include <QtWidgets/QHeaderView>
#include <QtWidgets/QMainWindow>
#include <QtWidgets/QMenuBar>
#include <QtWidgets/QPushButton>
#include <QtWidgets/QStatusBar>
#include <QtWidgets/QToolBar>
#include <QtWidgets/QWidget>

QT_BEGIN_NAMESPACE

class Ui_MainWindow
{
public:
    QWidget *centralWidget;
    QFrame *frame;
    QPushButton *pushButton_6;
    QPushButton *pushButton_3;
    QPushButton *pushButton_5;
    QPushButton *pushButton_8;
    QPushButton *pushButton_2;
    QPushButton *pushButton_4;
    QPushButton *pushButton_7;
    QPushButton *pushButton;
    QPushButton *pushButton_9;
    QFrame *frame_2;
    QPushButton *pushButton_19;
    QPushButton *pushButton_20;
    QPushButton *pushButton_21;
    QPushButton *pushButton_22;
    QPushButton *pushButton_23;
    QPushButton *pushButton_24;
    QPushButton *pushButton_25;
    QPushButton *pushButton_26;
    QPushButton *pushButton_27;
    QFrame *frame_3;
    QPushButton *pushButton_28;
    QPushButton *pushButton_29;
    QPushButton *pushButton_30;
    QPushButton *pushButton_31;
    QPushButton *pushButton_32;
    QPushButton *pushButton_33;
    QPushButton *pushButton_34;
    QPushButton *pushButton_35;
    QPushButton *pushButton_36;
    QFrame *frame_4;
    QPushButton *pushButton_37;
    QPushButton *pushButton_38;
    QPushButton *pushButton_39;
    QPushButton *pushButton_40;
    QPushButton *pushButton_41;
    QPushButton *pushButton_42;
    QPushButton *pushButton_43;
    QPushButton *pushButton_44;
    QPushButton *pushButton_45;
    QFrame *frame_5;
    QPushButton *pushButton_46;
    QPushButton *pushButton_47;
    QPushButton *pushButton_48;
    QPushButton *pushButton_49;
    QPushButton *pushButton_50;
    QPushButton *pushButton_51;
    QPushButton *pushButton_52;
    QPushButton *pushButton_53;
    QPushButton *pushButton_54;
    QFrame *frame_6;
    QPushButton *pushButton_55;
    QPushButton *pushButton_56;
    QPushButton *pushButton_57;
    QPushButton *pushButton_58;
    QPushButton *pushButton_59;
    QPushButton *pushButton_60;
    QPushButton *pushButton_61;
    QPushButton *pushButton_62;
    QPushButton *pushButton_63;
    QFrame *frame_7;
    QPushButton *pushButton_64;
    QPushButton *pushButton_65;
    QPushButton *pushButton_66;
    QPushButton *pushButton_67;
    QPushButton *pushButton_68;
    QPushButton *pushButton_69;
    QPushButton *pushButton_70;
    QPushButton *pushButton_71;
    QPushButton *pushButton_72;
    QFrame *frame_8;
    QPushButton *pushButton_82;
    QPushButton *pushButton_83;
    QPushButton *pushButton_84;
    QPushButton *pushButton_85;
    QPushButton *pushButton_86;
    QPushButton *pushButton_87;
    QPushButton *pushButton_88;
    QPushButton *pushButton_89;
    QPushButton *pushButton_90;
    QFrame *frame_9;
    QPushButton *pushButton_91;
    QPushButton *pushButton_92;
    QPushButton *pushButton_93;
    QPushButton *pushButton_94;
    QPushButton *pushButton_95;
    QPushButton *pushButton_96;
    QPushButton *pushButton_97;
    QPushButton *pushButton_98;
    QPushButton *pushButton_99;
    QMenuBar *menuBar;
    QStatusBar *statusBar;
    QToolBar *toolBar;

    void setupUi(QMainWindow *MainWindow)
    {
        if (MainWindow->objectName().isEmpty())
            MainWindow->setObjectName(QStringLiteral("MainWindow"));
        MainWindow->resize(459, 497);
        centralWidget = new QWidget(MainWindow);
        centralWidget->setObjectName(QStringLiteral("centralWidget"));
        frame = new QFrame(centralWidget);
        frame->setObjectName(QStringLiteral("frame"));
        frame->setGeometry(QRect(60, 50, 111, 111));
        frame->setFrameShape(QFrame::StyledPanel);
        frame->setFrameShadow(QFrame::Raised);
        pushButton_6 = new QPushButton(frame);
        pushButton_6->setObjectName(QStringLiteral("pushButton_6"));
        pushButton_6->setGeometry(QRect(10, 40, 31, 27));
        pushButton_3 = new QPushButton(frame);
        pushButton_3->setObjectName(QStringLiteral("pushButton_3"));
        pushButton_3->setGeometry(QRect(70, 10, 31, 27));
        pushButton_5 = new QPushButton(frame);
        pushButton_5->setObjectName(QStringLiteral("pushButton_5"));
        pushButton_5->setGeometry(QRect(70, 40, 31, 27));
        pushButton_8 = new QPushButton(frame);
        pushButton_8->setObjectName(QStringLiteral("pushButton_8"));
        pushButton_8->setGeometry(QRect(40, 70, 31, 27));
        pushButton_2 = new QPushButton(frame);
        pushButton_2->setObjectName(QStringLiteral("pushButton_2"));
        pushButton_2->setGeometry(QRect(10, 10, 31, 27));
        pushButton_4 = new QPushButton(frame);
        pushButton_4->setObjectName(QStringLiteral("pushButton_4"));
        pushButton_4->setGeometry(QRect(40, 40, 31, 27));
        pushButton_7 = new QPushButton(frame);
        pushButton_7->setObjectName(QStringLiteral("pushButton_7"));
        pushButton_7->setGeometry(QRect(10, 70, 31, 27));
        pushButton = new QPushButton(frame);
        pushButton->setObjectName(QStringLiteral("pushButton"));
        pushButton->setGeometry(QRect(40, 10, 31, 27));
        pushButton_9 = new QPushButton(frame);
        pushButton_9->setObjectName(QStringLiteral("pushButton_9"));
        pushButton_9->setGeometry(QRect(70, 70, 31, 27));
        frame_2 = new QFrame(centralWidget);
        frame_2->setObjectName(QStringLiteral("frame_2"));
        frame_2->setGeometry(QRect(170, 50, 111, 111));
        frame_2->setFrameShape(QFrame::StyledPanel);
        frame_2->setFrameShadow(QFrame::Raised);
        pushButton_19 = new QPushButton(frame_2);
        pushButton_19->setObjectName(QStringLiteral("pushButton_19"));
        pushButton_19->setGeometry(QRect(10, 40, 31, 27));
        pushButton_20 = new QPushButton(frame_2);
        pushButton_20->setObjectName(QStringLiteral("pushButton_20"));
        pushButton_20->setGeometry(QRect(70, 10, 31, 27));
        pushButton_21 = new QPushButton(frame_2);
        pushButton_21->setObjectName(QStringLiteral("pushButton_21"));
        pushButton_21->setGeometry(QRect(70, 40, 31, 27));
        pushButton_22 = new QPushButton(frame_2);
        pushButton_22->setObjectName(QStringLiteral("pushButton_22"));
        pushButton_22->setGeometry(QRect(40, 70, 31, 27));
        pushButton_23 = new QPushButton(frame_2);
        pushButton_23->setObjectName(QStringLiteral("pushButton_23"));
        pushButton_23->setGeometry(QRect(10, 10, 31, 27));
        pushButton_24 = new QPushButton(frame_2);
        pushButton_24->setObjectName(QStringLiteral("pushButton_24"));
        pushButton_24->setGeometry(QRect(40, 40, 31, 27));
        pushButton_25 = new QPushButton(frame_2);
        pushButton_25->setObjectName(QStringLiteral("pushButton_25"));
        pushButton_25->setGeometry(QRect(10, 70, 31, 27));
        pushButton_26 = new QPushButton(frame_2);
        pushButton_26->setObjectName(QStringLiteral("pushButton_26"));
        pushButton_26->setGeometry(QRect(40, 10, 31, 27));
        pushButton_27 = new QPushButton(frame_2);
        pushButton_27->setObjectName(QStringLiteral("pushButton_27"));
        pushButton_27->setGeometry(QRect(70, 70, 31, 27));
        frame_3 = new QFrame(centralWidget);
        frame_3->setObjectName(QStringLiteral("frame_3"));
        frame_3->setGeometry(QRect(280, 50, 111, 111));
        frame_3->setFrameShape(QFrame::StyledPanel);
        frame_3->setFrameShadow(QFrame::Raised);
        pushButton_28 = new QPushButton(frame_3);
        pushButton_28->setObjectName(QStringLiteral("pushButton_28"));
        pushButton_28->setGeometry(QRect(10, 40, 31, 27));
        pushButton_29 = new QPushButton(frame_3);
        pushButton_29->setObjectName(QStringLiteral("pushButton_29"));
        pushButton_29->setGeometry(QRect(70, 10, 31, 27));
        pushButton_30 = new QPushButton(frame_3);
        pushButton_30->setObjectName(QStringLiteral("pushButton_30"));
        pushButton_30->setGeometry(QRect(70, 40, 31, 27));
        pushButton_31 = new QPushButton(frame_3);
        pushButton_31->setObjectName(QStringLiteral("pushButton_31"));
        pushButton_31->setGeometry(QRect(40, 70, 31, 27));
        pushButton_32 = new QPushButton(frame_3);
        pushButton_32->setObjectName(QStringLiteral("pushButton_32"));
        pushButton_32->setGeometry(QRect(10, 10, 31, 27));
        pushButton_33 = new QPushButton(frame_3);
        pushButton_33->setObjectName(QStringLiteral("pushButton_33"));
        pushButton_33->setGeometry(QRect(40, 40, 31, 27));
        pushButton_34 = new QPushButton(frame_3);
        pushButton_34->setObjectName(QStringLiteral("pushButton_34"));
        pushButton_34->setGeometry(QRect(10, 70, 31, 27));
        pushButton_35 = new QPushButton(frame_3);
        pushButton_35->setObjectName(QStringLiteral("pushButton_35"));
        pushButton_35->setGeometry(QRect(40, 10, 31, 27));
        pushButton_36 = new QPushButton(frame_3);
        pushButton_36->setObjectName(QStringLiteral("pushButton_36"));
        pushButton_36->setGeometry(QRect(70, 70, 31, 27));
        frame_4 = new QFrame(centralWidget);
        frame_4->setObjectName(QStringLiteral("frame_4"));
        frame_4->setGeometry(QRect(60, 160, 111, 111));
        frame_4->setFrameShape(QFrame::StyledPanel);
        frame_4->setFrameShadow(QFrame::Raised);
        pushButton_37 = new QPushButton(frame_4);
        pushButton_37->setObjectName(QStringLiteral("pushButton_37"));
        pushButton_37->setGeometry(QRect(10, 40, 31, 27));
        pushButton_38 = new QPushButton(frame_4);
        pushButton_38->setObjectName(QStringLiteral("pushButton_38"));
        pushButton_38->setGeometry(QRect(70, 10, 31, 27));
        pushButton_39 = new QPushButton(frame_4);
        pushButton_39->setObjectName(QStringLiteral("pushButton_39"));
        pushButton_39->setGeometry(QRect(70, 40, 31, 27));
        pushButton_40 = new QPushButton(frame_4);
        pushButton_40->setObjectName(QStringLiteral("pushButton_40"));
        pushButton_40->setGeometry(QRect(40, 70, 31, 27));
        pushButton_41 = new QPushButton(frame_4);
        pushButton_41->setObjectName(QStringLiteral("pushButton_41"));
        pushButton_41->setGeometry(QRect(10, 10, 31, 27));
        pushButton_42 = new QPushButton(frame_4);
        pushButton_42->setObjectName(QStringLiteral("pushButton_42"));
        pushButton_42->setGeometry(QRect(40, 40, 31, 27));
        pushButton_43 = new QPushButton(frame_4);
        pushButton_43->setObjectName(QStringLiteral("pushButton_43"));
        pushButton_43->setGeometry(QRect(10, 70, 31, 27));
        pushButton_44 = new QPushButton(frame_4);
        pushButton_44->setObjectName(QStringLiteral("pushButton_44"));
        pushButton_44->setGeometry(QRect(40, 10, 31, 27));
        pushButton_45 = new QPushButton(frame_4);
        pushButton_45->setObjectName(QStringLiteral("pushButton_45"));
        pushButton_45->setGeometry(QRect(70, 70, 31, 27));
        frame_5 = new QFrame(centralWidget);
        frame_5->setObjectName(QStringLiteral("frame_5"));
        frame_5->setGeometry(QRect(170, 160, 111, 111));
        frame_5->setFrameShape(QFrame::StyledPanel);
        frame_5->setFrameShadow(QFrame::Raised);
        pushButton_46 = new QPushButton(frame_5);
        pushButton_46->setObjectName(QStringLiteral("pushButton_46"));
        pushButton_46->setGeometry(QRect(10, 40, 31, 27));
        pushButton_47 = new QPushButton(frame_5);
        pushButton_47->setObjectName(QStringLiteral("pushButton_47"));
        pushButton_47->setGeometry(QRect(70, 10, 31, 27));
        pushButton_48 = new QPushButton(frame_5);
        pushButton_48->setObjectName(QStringLiteral("pushButton_48"));
        pushButton_48->setGeometry(QRect(70, 40, 31, 27));
        pushButton_49 = new QPushButton(frame_5);
        pushButton_49->setObjectName(QStringLiteral("pushButton_49"));
        pushButton_49->setGeometry(QRect(40, 70, 31, 27));
        pushButton_50 = new QPushButton(frame_5);
        pushButton_50->setObjectName(QStringLiteral("pushButton_50"));
        pushButton_50->setGeometry(QRect(10, 10, 31, 27));
        pushButton_51 = new QPushButton(frame_5);
        pushButton_51->setObjectName(QStringLiteral("pushButton_51"));
        pushButton_51->setGeometry(QRect(40, 40, 31, 27));
        pushButton_52 = new QPushButton(frame_5);
        pushButton_52->setObjectName(QStringLiteral("pushButton_52"));
        pushButton_52->setGeometry(QRect(10, 70, 31, 27));
        pushButton_53 = new QPushButton(frame_5);
        pushButton_53->setObjectName(QStringLiteral("pushButton_53"));
        pushButton_53->setGeometry(QRect(40, 10, 31, 27));
        pushButton_54 = new QPushButton(frame_5);
        pushButton_54->setObjectName(QStringLiteral("pushButton_54"));
        pushButton_54->setGeometry(QRect(70, 70, 31, 27));
        frame_6 = new QFrame(centralWidget);
        frame_6->setObjectName(QStringLiteral("frame_6"));
        frame_6->setGeometry(QRect(280, 160, 111, 111));
        frame_6->setFrameShape(QFrame::StyledPanel);
        frame_6->setFrameShadow(QFrame::Raised);
        pushButton_55 = new QPushButton(frame_6);
        pushButton_55->setObjectName(QStringLiteral("pushButton_55"));
        pushButton_55->setGeometry(QRect(10, 40, 31, 27));
        pushButton_56 = new QPushButton(frame_6);
        pushButton_56->setObjectName(QStringLiteral("pushButton_56"));
        pushButton_56->setGeometry(QRect(70, 10, 31, 27));
        pushButton_57 = new QPushButton(frame_6);
        pushButton_57->setObjectName(QStringLiteral("pushButton_57"));
        pushButton_57->setGeometry(QRect(70, 40, 31, 27));
        pushButton_58 = new QPushButton(frame_6);
        pushButton_58->setObjectName(QStringLiteral("pushButton_58"));
        pushButton_58->setGeometry(QRect(40, 70, 31, 27));
        pushButton_59 = new QPushButton(frame_6);
        pushButton_59->setObjectName(QStringLiteral("pushButton_59"));
        pushButton_59->setGeometry(QRect(10, 10, 31, 27));
        pushButton_60 = new QPushButton(frame_6);
        pushButton_60->setObjectName(QStringLiteral("pushButton_60"));
        pushButton_60->setGeometry(QRect(40, 40, 31, 27));
        pushButton_61 = new QPushButton(frame_6);
        pushButton_61->setObjectName(QStringLiteral("pushButton_61"));
        pushButton_61->setGeometry(QRect(10, 70, 31, 27));
        pushButton_62 = new QPushButton(frame_6);
        pushButton_62->setObjectName(QStringLiteral("pushButton_62"));
        pushButton_62->setGeometry(QRect(40, 10, 31, 27));
        pushButton_63 = new QPushButton(frame_6);
        pushButton_63->setObjectName(QStringLiteral("pushButton_63"));
        pushButton_63->setGeometry(QRect(70, 70, 31, 27));
        frame_7 = new QFrame(centralWidget);
        frame_7->setObjectName(QStringLiteral("frame_7"));
        frame_7->setGeometry(QRect(60, 270, 111, 111));
        frame_7->setFrameShape(QFrame::StyledPanel);
        frame_7->setFrameShadow(QFrame::Raised);
        pushButton_64 = new QPushButton(frame_7);
        pushButton_64->setObjectName(QStringLiteral("pushButton_64"));
        pushButton_64->setGeometry(QRect(10, 40, 31, 27));
        pushButton_65 = new QPushButton(frame_7);
        pushButton_65->setObjectName(QStringLiteral("pushButton_65"));
        pushButton_65->setGeometry(QRect(70, 10, 31, 27));
        pushButton_66 = new QPushButton(frame_7);
        pushButton_66->setObjectName(QStringLiteral("pushButton_66"));
        pushButton_66->setGeometry(QRect(70, 40, 31, 27));
        pushButton_67 = new QPushButton(frame_7);
        pushButton_67->setObjectName(QStringLiteral("pushButton_67"));
        pushButton_67->setGeometry(QRect(40, 70, 31, 27));
        pushButton_68 = new QPushButton(frame_7);
        pushButton_68->setObjectName(QStringLiteral("pushButton_68"));
        pushButton_68->setGeometry(QRect(10, 10, 31, 27));
        pushButton_69 = new QPushButton(frame_7);
        pushButton_69->setObjectName(QStringLiteral("pushButton_69"));
        pushButton_69->setGeometry(QRect(40, 40, 31, 27));
        pushButton_70 = new QPushButton(frame_7);
        pushButton_70->setObjectName(QStringLiteral("pushButton_70"));
        pushButton_70->setGeometry(QRect(10, 70, 31, 27));
        pushButton_71 = new QPushButton(frame_7);
        pushButton_71->setObjectName(QStringLiteral("pushButton_71"));
        pushButton_71->setGeometry(QRect(40, 10, 31, 27));
        pushButton_72 = new QPushButton(frame_7);
        pushButton_72->setObjectName(QStringLiteral("pushButton_72"));
        pushButton_72->setGeometry(QRect(70, 70, 31, 27));
        frame_8 = new QFrame(centralWidget);
        frame_8->setObjectName(QStringLiteral("frame_8"));
        frame_8->setGeometry(QRect(170, 270, 111, 111));
        frame_8->setFrameShape(QFrame::StyledPanel);
        frame_8->setFrameShadow(QFrame::Raised);
        pushButton_82 = new QPushButton(frame_8);
        pushButton_82->setObjectName(QStringLiteral("pushButton_82"));
        pushButton_82->setGeometry(QRect(10, 40, 31, 27));
        pushButton_83 = new QPushButton(frame_8);
        pushButton_83->setObjectName(QStringLiteral("pushButton_83"));
        pushButton_83->setGeometry(QRect(70, 10, 31, 27));
        pushButton_84 = new QPushButton(frame_8);
        pushButton_84->setObjectName(QStringLiteral("pushButton_84"));
        pushButton_84->setGeometry(QRect(70, 40, 31, 27));
        pushButton_85 = new QPushButton(frame_8);
        pushButton_85->setObjectName(QStringLiteral("pushButton_85"));
        pushButton_85->setGeometry(QRect(40, 70, 31, 27));
        pushButton_86 = new QPushButton(frame_8);
        pushButton_86->setObjectName(QStringLiteral("pushButton_86"));
        pushButton_86->setGeometry(QRect(10, 10, 31, 27));
        pushButton_87 = new QPushButton(frame_8);
        pushButton_87->setObjectName(QStringLiteral("pushButton_87"));
        pushButton_87->setGeometry(QRect(40, 40, 31, 27));
        pushButton_88 = new QPushButton(frame_8);
        pushButton_88->setObjectName(QStringLiteral("pushButton_88"));
        pushButton_88->setGeometry(QRect(10, 70, 31, 27));
        pushButton_89 = new QPushButton(frame_8);
        pushButton_89->setObjectName(QStringLiteral("pushButton_89"));
        pushButton_89->setGeometry(QRect(40, 10, 31, 27));
        pushButton_90 = new QPushButton(frame_8);
        pushButton_90->setObjectName(QStringLiteral("pushButton_90"));
        pushButton_90->setGeometry(QRect(70, 70, 31, 27));
        frame_9 = new QFrame(centralWidget);
        frame_9->setObjectName(QStringLiteral("frame_9"));
        frame_9->setGeometry(QRect(280, 270, 111, 111));
        frame_9->setFrameShape(QFrame::StyledPanel);
        frame_9->setFrameShadow(QFrame::Raised);
        pushButton_91 = new QPushButton(frame_9);
        pushButton_91->setObjectName(QStringLiteral("pushButton_91"));
        pushButton_91->setGeometry(QRect(10, 40, 31, 27));
        pushButton_92 = new QPushButton(frame_9);
        pushButton_92->setObjectName(QStringLiteral("pushButton_92"));
        pushButton_92->setGeometry(QRect(70, 10, 31, 27));
        pushButton_93 = new QPushButton(frame_9);
        pushButton_93->setObjectName(QStringLiteral("pushButton_93"));
        pushButton_93->setGeometry(QRect(70, 40, 31, 27));
        pushButton_94 = new QPushButton(frame_9);
        pushButton_94->setObjectName(QStringLiteral("pushButton_94"));
        pushButton_94->setGeometry(QRect(40, 70, 31, 27));
        pushButton_95 = new QPushButton(frame_9);
        pushButton_95->setObjectName(QStringLiteral("pushButton_95"));
        pushButton_95->setGeometry(QRect(10, 10, 31, 27));
        pushButton_96 = new QPushButton(frame_9);
        pushButton_96->setObjectName(QStringLiteral("pushButton_96"));
        pushButton_96->setGeometry(QRect(40, 40, 31, 27));
        pushButton_97 = new QPushButton(frame_9);
        pushButton_97->setObjectName(QStringLiteral("pushButton_97"));
        pushButton_97->setGeometry(QRect(10, 70, 31, 27));
        pushButton_98 = new QPushButton(frame_9);
        pushButton_98->setObjectName(QStringLiteral("pushButton_98"));
        pushButton_98->setGeometry(QRect(40, 10, 31, 27));
        pushButton_99 = new QPushButton(frame_9);
        pushButton_99->setObjectName(QStringLiteral("pushButton_99"));
        pushButton_99->setGeometry(QRect(70, 70, 31, 27));
        MainWindow->setCentralWidget(centralWidget);
        menuBar = new QMenuBar(MainWindow);
        menuBar->setObjectName(QStringLiteral("menuBar"));
        menuBar->setGeometry(QRect(0, 0, 459, 25));
        MainWindow->setMenuBar(menuBar);
        statusBar = new QStatusBar(MainWindow);
        statusBar->setObjectName(QStringLiteral("statusBar"));
        MainWindow->setStatusBar(statusBar);
        toolBar = new QToolBar(MainWindow);
        toolBar->setObjectName(QStringLiteral("toolBar"));
        MainWindow->addToolBar(Qt::TopToolBarArea, toolBar);
        MainWindow->insertToolBarBreak(toolBar);

        retranslateUi(MainWindow);

        QMetaObject::connectSlotsByName(MainWindow);
    } // setupUi

    void retranslateUi(QMainWindow *MainWindow)
    {
        MainWindow->setWindowTitle(QApplication::translate("MainWindow", "MainWindow", 0));
        pushButton_6->setText(QString());
        pushButton_3->setText(QString());
        pushButton_5->setText(QString());
        pushButton_8->setText(QString());
        pushButton_2->setText(QString());
        pushButton_4->setText(QString());
        pushButton_7->setText(QString());
        pushButton->setText(QString());
        pushButton_9->setText(QString());
        pushButton_19->setText(QString());
        pushButton_20->setText(QString());
        pushButton_21->setText(QString());
        pushButton_22->setText(QString());
        pushButton_23->setText(QString());
        pushButton_24->setText(QString());
        pushButton_25->setText(QString());
        pushButton_26->setText(QString());
        pushButton_27->setText(QString());
        pushButton_28->setText(QString());
        pushButton_29->setText(QString());
        pushButton_30->setText(QString());
        pushButton_31->setText(QString());
        pushButton_32->setText(QString());
        pushButton_33->setText(QString());
        pushButton_34->setText(QString());
        pushButton_35->setText(QString());
        pushButton_36->setText(QString());
        pushButton_37->setText(QString());
        pushButton_38->setText(QString());
        pushButton_39->setText(QString());
        pushButton_40->setText(QString());
        pushButton_41->setText(QString());
        pushButton_42->setText(QString());
        pushButton_43->setText(QString());
        pushButton_44->setText(QString());
        pushButton_45->setText(QString());
        pushButton_46->setText(QString());
        pushButton_47->setText(QString());
        pushButton_48->setText(QString());
        pushButton_49->setText(QString());
        pushButton_50->setText(QString());
        pushButton_51->setText(QString());
        pushButton_52->setText(QString());
        pushButton_53->setText(QString());
        pushButton_54->setText(QString());
        pushButton_55->setText(QString());
        pushButton_56->setText(QString());
        pushButton_57->setText(QString());
        pushButton_58->setText(QString());
        pushButton_59->setText(QString());
        pushButton_60->setText(QString());
        pushButton_61->setText(QString());
        pushButton_62->setText(QString());
        pushButton_63->setText(QString());
        pushButton_64->setText(QString());
        pushButton_65->setText(QString());
        pushButton_66->setText(QString());
        pushButton_67->setText(QString());
        pushButton_68->setText(QString());
        pushButton_69->setText(QString());
        pushButton_70->setText(QString());
        pushButton_71->setText(QString());
        pushButton_72->setText(QString());
        pushButton_82->setText(QString());
        pushButton_83->setText(QString());
        pushButton_84->setText(QString());
        pushButton_85->setText(QString());
        pushButton_86->setText(QString());
        pushButton_87->setText(QString());
        pushButton_88->setText(QString());
        pushButton_89->setText(QString());
        pushButton_90->setText(QString());
        pushButton_91->setText(QString());
        pushButton_92->setText(QString());
        pushButton_93->setText(QString());
        pushButton_94->setText(QString());
        pushButton_95->setText(QString());
        pushButton_96->setText(QString());
        pushButton_97->setText(QString());
        pushButton_98->setText(QString());
        pushButton_99->setText(QString());
        toolBar->setWindowTitle(QApplication::translate("MainWindow", "toolBar", 0));
    } // retranslateUi

};

namespace Ui {
    class MainWindow: public Ui_MainWindow {};
} // namespace Ui

QT_END_NAMESPACE

#endif // UI_MAINWINDOW_H
